using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

[System.Serializable]
public class GameData {
    public bool newGame;
    public int curCharNum;
    public int newCharNum;
    public int tsLevel;
    public int tsSub;
    public int tsWeaponAcc;
    public int tsWeaponSpd;
    public int tsWeaponDmg;
    public int tsWeaponDef;
    public string[] tsItemNames;
    public string[] tsItemTypes;
    public string[] tsItemMods;
    public string[] floorItemNames;
    public string[] floorItemTypes;
    public string[] floorItemMods;
    public string[] merchantItemNames;
    public string[] merchantItemTypes;
    public string[] merchantItemMods;
    public string[] resumeItemNames;
    public string[] resumeItemTypes;
    public string[] resumeItemMods;
    public int resumeLevel;
    public int resumeSub;
    public int resumeAcc;
    public int resumeSpd;
    public int resumeDmg;
    public int resumeDef;
    public int potionAcc;
    public int potionSpd;
    public int potionDmg;
    public int potionDef;
    public int playerStamina;
    public int enemyStamina;
    public List<int> diceNumbers;
    public List<string> diceTypes;
    public List<string> dicePlayerOrEnemy;
    public List<string> diceAttachedToStat;
    public List<bool> diceRerolled;
    public List<string> playerWounds;
    public List<string> enemyWounds;
    public int enemyNum;
    public bool usedMace;
    public bool usedAnkh;
    public bool usedHelm;
    public bool usedBoots;
    public int numItemsDroppedForTrade;
    public int discardableDieCounter;
    public bool enemyIsDead;
    public int enemyAcc;
    public int enemySpd;
    public int enemyDmg;
    public int enemyDef;

    public GameData() {
        curCharNum = 0;
        newCharNum = 0;
        tsLevel = -1;
        tsSub = -1;
        tsWeaponAcc = 0;
        tsWeaponSpd = 0;
        tsWeaponDmg = 0;
        tsWeaponDef = 0;
        tsItemNames = new string[9];
        tsItemTypes = new string[9];
        tsItemMods = new string[9];
        floorItemNames = new string[9];
        floorItemTypes = new string[9];
        floorItemMods = new string[9];
        merchantItemNames = new string[9];
        merchantItemTypes = new string[9];
        merchantItemMods = new string[9];
        resumeItemNames = new string[9];
        resumeItemTypes = new string[9];
        resumeItemMods = new string[9];
        resumeLevel = 0;
        resumeSub = 0;
        resumeAcc = 0;
        resumeSpd = 0;
        resumeDmg = 0;
        resumeDef = 0;
        potionAcc = 0;
        potionSpd = 0;
        potionDmg = 0;
        potionDef = 0;
        playerStamina = 0;
        enemyStamina = 0;
        diceNumbers = new List<int>();
        diceTypes = new List<string>();
        dicePlayerOrEnemy = new List<string>();
        diceAttachedToStat = new List<string>();
        diceRerolled = new List<bool>();
        playerWounds = new List<string>();
        enemyWounds = new List<string>();
        enemyNum = 0;
        usedMace = false;
        usedAnkh = false;
        usedHelm = false;
        usedBoots = false;
        numItemsDroppedForTrade = 0;
        discardableDieCounter = 0;
        enemyIsDead = false;
        enemyAcc = 0;
        enemySpd = 0;
        enemyDmg = 0;
        enemyDef = 0;
    }
}
